### ISSUE TITLE
SyntaxError: Unexpected token 'export' using in Nestjs

### ISSUE THREAD

**Issue by imranalisolanki** [bhar4t/upiqr#1]
![image](https://user-images.githubusercontent.com/50860156/192439122-63029352-4a34-42af-9b18-cad970669a8b.png)

**Comment by bhar4t** [comment]
Hi, sorry for addressing this issue very late, I've fixed this issue and also updated the document for the fix.
Thanks for raising the issue, you can also contribute in this package.
