### ISSUE TITLE
The library generates proper qr code as expected but the payment fails everytime

### ISSUE THREAD

**Issue by Omkarc284** [bhar4t/upiqr#2]
I have used this library in a project where it generates QR code for payment to the customer. By scanning it from Gpay or phonepe it shows correctly the Receivers VPA and the amount to be paid but the payment fails every time meanwhile the QR code which the client already uses for the payment works perfectly indicating there's no bank server issue

**Comment by navinkrv** [comment]
try using merchant UPI for qr generation

**Comment by Guchii** [comment]
Happened with me as well, not with bhar4t/upiqr but I implemented something similar, there the QRs were partially working (only amount, and payeeVPA) but the payments failed with the intent links. We are missing something very important, Sadly this isn't documented well enough anywhere :( 
see this: https://www.labnol.org/files/linking.pdf

**Comment by navinkrv** [comment]
Works well with phonepe merchant upi ids

**Comment by bhar4t** [comment]
This seems to be API/server issue, hence closing the issue, Thanks!
