### ISSUE TITLE
upi intent flow not working

### ISSUE THREAD

**Issue by mohit7067** [bhar4t/upiqr#6]
upi intent flow is not working using the package if we create a link it only open the app but after filling the upi pin the upi gives error

**Comment by raka334** [comment]
+1

**Comment by bhar4t** [comment]
Do you have error message details or screenshot? Please attach if possible.

**Comment by raka334** [comment]
![image](https://github.com/user-attachments/assets/e00e5d61-c539-4ed7-a6d7-bd417630a93d)
This error occurs in all apps 
![Uploading image.png…]()
These are the error message i got

**Comment by raka334** [comment]
![Screenshot_20240716-224442_PayZapp](https://github.com/user-attachments/assets/3984349e-3ed7-41ee-a0d0-d7c5fb00c7be)
![Screenshot_20240716-224159_WhatsApp](https://github.com/user-attachments/assets/f9dac799-fc89-4c80-8785-b79c694f5e21)
These are the errors i got when i visit through link 
any fix for this
