### ISSUE TITLE
Callback URL

### ISSUE THREAD

**Issue by chetan-SMRI** [bhar4t/upiqr#7]
I wanted to know how will the callback url be traced when it returns that payment is successful, and how can we verify that its succesfull and someone just didnt hit it directly without making payment......

is it possible?

**Comment by bhar4t** [comment]
Hi @chetan-SMRI, This package doesn't makes any transactions with a bank and No any API is involved in this package; it is solely designed to generate UPI QR codes or intents using the specific information provided in the description. For transactions, you should use other APIs that can effectively fulfill that purpose.

Closing the issue, Thanks!
